### ISSUE TITLE
Consider publishing plugin as self-contained app

### ISSUE THREAD

**Issue by dtivel** [microsoft/artifacts-credprovider#112]
If not published as a self-contained app, a NuGet launch of the plugin could fail if the plugin's runtime dependencies are not satisfied.

.NET Core ran into this failure because their build uses .NET Core 3.0 with multilevel lookup ([`DOTNET_MULTILEVEL_LOOKUP`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#environment-variables)) disabled.

**Comment by zarenner** [comment]
After consulting with .NET Core experts, I think supporting major version roll-forward would be a better alternative.

Running self-contained would also work, but adds a bunch of complexity:
1. Requires distributing the credprovider for multiple platforms, in addition to the framework-dependent release today. Confusing.
2. For use in our upcoming authentication tasks, would require detecting the platform, and possibly requires bundling multiple platforms with the task, which makes the task download an unreasonable size.
3. Requires changes to nuget/dotnet to invoke plugins as executables, or requires running the self-contained app via dotnet exec which is odd.

Major version roll-forward also has risks due to breaking changes in .NET Core, but these risks should be much easier to manage and test for.

**Comment by jcagme** [comment]
Just curious if there is an ETA for either of the solutions, we know that once either CredProvider is a self-contained app or roll-forward things will work for us and it will be easier now with the introduction of authentication tasks which I just tried and fail the same way as setting CredProvider manually.

**Comment by zarenner** [comment]
@jcagme just released 0.1.18 of the credprovider with roll-forward. Could you please give that a try?

**Comment by zarenner** [comment]
Closing as .NET Core 3.0 is now supported via major version roll-forward. Will not be publishing as a self-contained app since it would require many changes as described above.

Please let me know if you have any issues on .NET Core 3.0.
