### ISSUE TITLE
Question: How do you force token acquisition

### ISSUE THREAD

**Issue by lukewis** [microsoft/artifacts-credprovider#118]
I just installed the credential provider via the helper script on macOS.  I'm now trying to install a global tool from a private azure feed, but it's coming up with a package not found error.  I suspect this is because I haven't yet acquired a token.  The README says to run dotnet restore --interactive, but I don't have a project against which I can restore (since I'm trying to install a global tool).  Is there another way to force it to acquire a token?

**Comment by apluche** [comment]
Hi,

Could you try running the credential provider dll directly with the -I (IsRetry) flag? 

The .dll path is \.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll 

Here is an example of a command: .\CredentialProvider.Microsoft.dll -U <feed url here> -I

Otherwise, this link might provide some useful information about the command.
[Help](https://github.com/microsoft/artifacts-credprovider#help)

Please let me know what happens. I gladly help you figure out the issue if you are still running into it!

**Comment by lukewis** [comment]
Thanks for the tip @apluche !  That did in fact succeed in acquiring a token.  I then learned that although I had run a nuget.exe command to add the private source, it did not alter my ~/.nuget/Nuget/Nuget.config file (not sure where nuget.exe stored that information).  After I manually edited the user Nuget.config file to include my private feed, I was able to install the global tool.  It's too bad that dotnet cli doesn't have a dotnet list packagesource or dotnet add packagesource commands.  Thanks again for the tip!
