### ISSUE TITLE
Can't get 'installcredprovider.ps1' working with 'mcr.microsoft.com/dotnet/core/sdk:3.0'

### ISSUE THREAD

**Issue by sakowiczm** [microsoft/artifacts-credprovider#148]
Hi Guys,

I'm trying to get `installcredprovider.ps1` working with `mcr.microsoft.com/dotnet/core/sdk:3.0` - without a luck.
Docker file I'm using:

```
# escape=`

ARG PAT
ARG FEED

FROM mcr.microsoft.com/dotnet/core/sdk:3.0

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
                       
RUN Invoke-WebRequest 'https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1' -OutFile installcredprovider.ps1; `
    .\installcredprovider.ps1 -Version "0.1.19" -Force ` 
    Remove-Item .\installcredprovider.ps1;

ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED=true
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS='{"endpointCredentials": [{"endpoint":"$(FEED)", "username":"build", "password":"$(PAT)"}]}'

# dotnet copy, restore & build
...
```

When I don't specify `Version` I'm getting error that `Unable to find the release version`. Also blows up when I specify version = `0.1.20`
When I specify the version installation is successful but `dotnet restore` fails with `Response status code does not indicate success: 401 (Unauthorized).`
Credentials are fine they work when I put them in the `Nuget.config` file.
Poking around: 
- script installs `netcore` plugin in `c:\.nuget\plugins`.
- nothing is present in `$env:USERPROFILE\.nuget\plugins` folder.
- no `NUGET_PLUGIN_PATHS` env variable defined
- if I define `NUGET_PLUGIN_PATHS` and point toward `C:\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll` - no exceptions thrown but `dotnet restore` still cannot authenticate.

Any ideas what is going wrong here?

**Comment by satbai** [comment]
Can you run `dotnet restore --interactive --verbosity detailed` and share the logs after the line "Using CredentialProvider.Microsoft.dll as a credential provider plugin." so we can investigate why authentication fails? Also, please make sure you're using dotnet SDK version 2.1.400 or later.

When it comes to the ps1 script installing the cred provider to the wrong location, it seems like for some reason your environment can't understand the [line ](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1#L25)`[System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile`. Have you tried the [.sh script](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.sh)?

**Comment by satbai** [comment]
There was an issue with the latest release name, 0.1.20 specifically, which resulted in not being able to use the install script to install that version, but that issue has now been fixed.

Are you still experiencing issues auth with `dotnet restore`?

**Comment by dasvacina** [comment]
I just came across this issue myself. 

I've used the .sh script a few times for Linux containers and it's worked like a charm. But now, due to project requirements, we have to run in Windows containers, and I'm having the same issue sakowiczm is with the ps1 file. 

I'm not very familiar with Powershell, but I did notice the dotnet/core/sdk:3.0 Dockerfile is installing 7.0.0-preview.4. When I run the Get-Command command in docker the list is a lot smaller than when I run the Get-Command command on my PC outside of docker (Powershell version 5.1). Any chance PS version differences are causing the issue?

**Comment by satbai** [comment]
I just added some verbose logging to the script. Could you please use the latest [script](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1) and running it with verbose logging. 
1. Turn verbosity on: $VerbosePreference = "continue"
2. run installcredprovider.ps1
3. And then turn verbosity back off: $VerbosePreference = "silentlycontinue" 

Maybe it gives some more info. @dasvacina does the script install the cred provider in the wrong location for you as well? If the script installs the cred provider to the wrong location, you could set the NUGET_PLUGIN_PATHS to the CredentialProvider.Microsoft.dll as a workaround. Does that work for you?

**Comment by dasvacina** [comment]
Setting the NUGET_PLUGIN_PATHS environment variable to the CredentialProvider.Microsoft.dll worked for me.

Thanks for the help.

**Comment by herenhuang** [comment]
There's been a code fix with a workaround in this thread. Please let us know if there's more blocking questions here.

**Comment by KevinBui1111** [comment]
The reason is Credential Provider is not install in C:\Users\<currentuser>\,
Because in docker image windows `microsoft.com/dotnet/core/sdk:3.0` can't resolve **[System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile** (emtpy string) (line 25 in installcredprovider.ps1)

Workaround: alter line 25, from:
`$profilePath = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile)`
to
`$profilePath = $env:USERPROFILE`

You need to add **local** installcredprovider.ps1 to **dockerfile** instead of the one from github

Your dockerfile will look like:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 AS build
WORKDIR /src
COPY ["abc/yourproject.csproj", "abc/"]
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{\"endpointCredentials\": [{\"endpoint\":\"https://pkgs.dev.azure.com/xxx/nuget/v3/index.json\", \"username\":\"aaa@bbb.com\", \"password\":\"xxxTokenSTRINGxxx\"}]}"

ADD installcredprovider.ps1 .
RUN pwsh -File ./installcredprovider.ps1
RUN dotnet nuget add source https://pkgs.dev.azure.com/xxx/nuget/v3/index.json -n PAB

RUN dotnet restore "abc/yourproject.csproj"

```
