### ISSUE TITLE
How to check artifactory token is expired or not.

### ISSUE THREAD

**Issue by dhmuralikrishna** [microsoft/artifacts-credprovider#165]
How can we validate the token is expired or not. I want to do it from PowerShell.

**Comment by noahpritt** [comment]
Are you referring to a PAT that is returned from credential provider? If so, I am not aware of a direct command from powershell to see if it is expired or not. However, here is a work-around that may achieve your goal. Try running this command:

`Invoke-WebRequest https://dev.azure.com/ORG_NAME_HERE/_apis/connectionData -Headers @{Authorization = "Basic $([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("azdev:$PAT")))"; "X-TFS-FedAuthRedirect" = "Suppress"}` 

This assumes that the PAT is in a variable named PAT. If this command fails, there's a good chance that it is caused by an expired PAT. (By the way, if you are not referring to PATs but rather something associated with Artifactory, that is a different product.)

**Comment by noahpritt** [comment]
You can also check if it is expired from the web - that's the most straight-forward way. Doesn't use powershell though.

**Comment by dhmuralikrishna** [comment]
Thank's this works
