### ISSUE TITLE
Dotnet Nuget Push Auth Issue

### ISSUE THREAD

**Issue by WoodProgrammer** [microsoft/artifacts-credprovider#182]
Hi all,
I have an issue with dotnet-cli that located on docker container , I installed `artifacts-credprovider` and then related with documentation I have added `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` as a env file but when I rune th `dotnet nuget push --source $MY_SOURCE ./package.nupkg` command it returning auth 401 error , How Can I solve this issue ? 

Dockerfile : 
```
FROM microsoft/dotnet:2.2-sdk AS build
RUN curl -s -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | bash
RUN VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{\"endpointCredentials\": [{\"endpoint\":\"https://pkgs.dev.azure.com/in3/_packaging/MY_SOURCE/nuget/v3/index.json\", \"username\":\"USERNAME\", \"password\":\"PAT\"}]}"
..
..
..

RUN dotnet nuget push --source "https://pkgs.dev.azure.com/in3/_packaging/MY_SOURCE/nuget/v3/index.json" --api-key az ./sample.nukpg

```

Error message : 

```
error: Unable to load the service index for source https://pkgs.dev.azure.com/in3/_packaging/MY_SOURCE/nuget/v3/index.json.
error:   Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by satbai** [comment]
Could you please edit your `RUN dotnet nuget push` command to add detailed verbosity? Then look from the verbose logs whether dotnet finds the cred provider plugin. The logs should say something like "Using path-to-CredentialProvider.Microsoft as a credential provider plugin.". If you don't see this in the log, it means that something went wrong when installing the cred provider. If it's there, please share the cred provider log so we can see what's happening. 

Note that it can also be a problem with the PAT that you've provided to the VSS_NUGET_EXTERNAL_FEED_ENDPOINTS variable. Make sure you're following[ these instructions ](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)when getting the PAT.

Also please note that we recommend using a [more recent version of dotnet](https://github.com/microsoft/artifacts-credprovider#dotnet) because it'll have some important bug fixes.

**Comment by WoodProgrammer** [comment]
I tried `mcr.microsoft.com/dotnet/core/sdk:3.1-buster` image updated token to the full-access even with that it still returning `Unable to load the service index for source` error .

Notice `verbosity` is a disabled on dotnet `3.1.201` version, how can I open that  ?

**Comment by satbai** [comment]
Weird if verbose logs are not available. To get verbose logs from the cred provider could you try running `dotnet restore --verbosity detailed` just for testing/debugging purposes? 

My other guess is that `dotnet nuget push` only uses the api key for authenticating and it skips the cred provider altogether. May be worth looking into that.

**Comment by edgarrs** [comment]
https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md
