### ISSUE TITLE
401 Unauthorized when trying to load nuget azure devops json on mac

### ISSUE THREAD

**Issue by Quyrean** [microsoft/artifacts-credprovider#190]
Hello, 

I am trying to use a nuget package that is hosted on an azure devops server and getting a 401 error.  I am running the commands in a mac shell.

```
$ dotnet restore --interactive
/usr/local/share/dotnet/sdk/3.1.202/NuGet.targets(124,5): error : Unable to load the service index for source https://*****.com/tfs/MACollection/_packaging/****/nuget/v3/index.json. [/Users/****/work/repos/service-user-management/UserManagementService.sln]
/usr/local/share/dotnet/sdk/3.1.202/NuGet.targets(124,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/Users/*****/work/repos/service-user-management/UserManagementService.sln]

```

 I am using a
 mac  (mojave 10.14.4).  
NuGet Version: 5.4.0.6315
.NET Core SDK Version:   3.1.202

I followed the instructions in the readme using the script on a mac, but am not prompted for credentials when running 

`    dotnet restore --interactive
`
I also tried including the config file on the command line.

`  dotnet restore --configfile ~/.config/NuGet/NuGet.Config --interactive
`
I tried using JetBrains rider and adding the credentials.  I tried using the "nuget sources add" command line.  I tried using a personal access token.  

I can download the file with the exact same user/pass when using wget.

I am attaching part of the log when I ran

```
dotnet restore --interactive -v d
```

I see this error but do not know what it means or how to fix it and google does not either :)

```
This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
```

Please let me know if you require further information.
thank you for your time.
[error.log](https://github.com/microsoft/artifacts-credprovider/files/4692168/error.log)
[dotnet-info.log](https://github.com/microsoft/artifacts-credprovider/files/4692170/dotnet-info.log)

**Comment by apluche** [comment]
Hi @Quyrean,

From the logs, it appears you are trying to access an on-prem deployment. Idealy, you wouldn't be using the artifacts-credprovider. You will likely need to use a PAT to authenticate on the server since artifacts-credprovider does not interface well with on-prem instances.

You can find more information on how to authenticate here: https://duanenewman.net/blog/post/2019-07-29-basic-auth-with-tfs-package-server/ . Nuget has a feature called ValidAuthenticationTypes (see PR here: https://github.com/NuGet/NuGet.Client/pull/2297) for this type of authentication.

We are providing better instructions in future on-prem releases. We apologize for the inconvenience.

**Comment by Quyrean** [comment]
Hi @apluche 

First thank you very very much for the reply!  Yes I am trying to access an on-prem deployment built for the azure devops pipeline.  I read the blog and it sounds exactly like my issue.  However when I try out the instructions, nuget still requests my credentials, and then does not load the packages.

```
$ nuget sources Add -Name "XXX" -Source "https://****.com/tfs/MACollection/_packaging/XXX/nuget/v3/index.json" -ValidAuthenticationTypes basic -username ***** -password '*****'

$ cat ~/.config/NuGet/NuGet.Config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="XXX" value="https://****.com/tfs/MACollection/_packaging/XXX/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <XXX>
      <add key="Username" value="*****" />
      <add key="Password" value="*****" />
      <add key="ValidAuthenticationTypes" value="basic" />
    </XXX>
  </packageSourceCredentials>
</configuration>

$ nuget restore -ConfigFile ~/.config/NuGet/NuGet.Config
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/15.0/bin'.
Restoring packages for /Users/*****/work/repos-******/service-user-management/API/UserManagementService.csproj...
  GET https://api.nuget.org/v3-flatcontainer/******.logging/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/******.logging/index.json 354ms
Using credentials from config. UserName: *****
Please provide credentials for: https://matfs.******-aws.com/tfs/MACollection/_packaging/XXX/nuget/v3/index.json
UserName: *****
Password: *****
Please provide credentials for: https://matfs.******-aws.com/tfs/MACollection/_packaging/XXX/nuget/v3/index.json
UserName: *****
Password: *****
Please provide credentials for: https://matfs.******-aws.com/tfs/MACollection/_packaging/XXX/nuget/v3/index.json
UserName: *****
Password: *****
Please provide credentials for: https://matfs.******-aws.com/tfs/MACollection/_packaging/XXX/nuget/v3/index.json
Unable to load the service index for source https://matfs.madss-aws.com/tfs/MACollection/_packaging/MADSS/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).
```

Any idea what I am doing wrong?

and thanks again!

**Comment by apluche** [comment]
Hi @Quyrean ,

Unfortunately the logs don't give me much to go off of. I do have a few questions for you however:
1. Did you use a PAT token as the password for the connection? 
2. Did you have to copy and paste it into the command line? There is sometimes an issue where the PAT isn't pasted correctly onto the command line. If it is this issue, you may need to find another way to paste the PAT in correctly.
3. In theory, the PAT in your config file should be enough to get the connection working. The username isn't used so that shouldn't be an issue.

**Comment by Quyrean** [comment]
Yay!  I was using my password, not an access token.  I changed the password to an access token and nuget restore is working now.  Thanks so much!  I searched for a long time and never found that page.
