### ISSUE TITLE
NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true but SessionTokenCache.dat not saved

### ISSUE THREAD

**Issue by mslichao** [microsoft/artifacts-credprovider#240]
I set environment variable NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED to true and set value of VSS_NUGET_EXTERNAL_FEED_ENDPOINTS, and the run dotnet restore.

Expect I can find SessionTokenCache.dat under ~/.local/share/MicrosoftCredentialProvider, but I can't find it.

So my question is how to work with NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED?

**Comment by satbai** [comment]
This is by design. The cred provider doesn't cache credentials when using the env var VSS_NUGET_EXTERNAL_FEED_ENDPOINTS, because the credentials are already provided with the environment variable. Because the creds are read from the variable, the cred provider doesn't need to do any extra work to get the crededentials, so basically there is no point in caching them. 

The NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED env var enables the token cache when using the interactive flow, aka when the VSS_NUGET_EXTERNAL_FEED_ENDPOINTS variable (or VSS_NUGET_ACCESSTOKEN) is not being used. The readme documentation isn't explaining this so I think we should update the readme to mention under [Session Token Cache Locations](https://github.com/microsoft/artifacts-credprovider#session-token-cache-locations) and [Environment Variables](https://github.com/microsoft/artifacts-credprovider#environment-variables) when the cache is actually used.

**Comment by mslichao** [comment]
Got it, thanks.
