### ISSUE TITLE
Bundle with nuget

### ISSUE THREAD

**Issue by letmaik** [Microsoft/artifacts-credprovider#34]
When I download git for Windows, then it has built-in support for 2FA for different providers like GitHub or VSTS.

Wouldn't it make sense to include this credential provider directly in the main nuget distribution? This would save projects from including installation instructions in their README files on how to get started with private Azure NuGet feeds. I consider this a problem, especially since this is only required when using the command line or VS Code. Opening a project in Visual Studio works out of the box as it has built-in integration with private Azure NuGet feeds and doesn't require any extra steps.

**Comment by alexmullans** [comment]
Because NuGet doesn't have a "distribution" in any sense other than "download this .exe file" from [here](https://www.nuget.org/downloads), we decided with @anangaur and others from the NuGet team not to do any bundling here. 

Separately, we are thinking about ways to build this into VS Code and into dotnet (which does have a distribution).

**Comment by rrelyea** [comment]
Note, as VS 2017 15.9 (or later) and VS Build SKU 2017 15.9 (or later) both install the credprovider, NuGet.exe 4.9 (or later) will be able to find that copy when run on that machine.
