### ISSUE TITLE
Inconsistent account selection modal behavior across operating systems

### ISSUE THREAD

**Issue by kartheekp-ms** [microsoft/artifacts-credprovider#465]
When executing the command `dotnet .\CredentialProvider.Microsoft -Uri {Azure Artifacts private feed URL} -IsRetry false -CanShowDialog` on Linux and Mac, the expected modal dialog, where users can select an account to obtain credentials, does not appear. Instead, the command displays device code login information, including a URL and device code for credential acquisition.

In contrast, on Windows and WSL, the same command prompts the user to select an account. If the user does not respond in time, it will revert to displaying the device code login information, including the URL and device code, in the console.

The [documentation](https://github.com/microsoft/artifacts-credprovider?tab=readme-ov-file#help) indicates that `CanShowDialog (-C) If true, the user can be prompted for credentials via UI; if false, the device flow must be used [Default='True']`. However, the UI prompt functions only on Windows and WSL, and not on other platforms.

**Comment by embetten** [comment]
For linux and mac the cred provider will not pop up a modal but will allow browser authentication. This is a MSAL limitation not something the cred provider has control over. 

However, the reason that canShowDialog is not working is because canshowdialog is hardcoded to false in nuget.client implementation. (see [definition](https://github.com/NuGet/NuGet.Client/blob/9dd33574b0cf5110692ee8e9401a39857fb5523a/src/NuGet.Core/NuGet.Credentials/DefaultCredentialServiceUtility.cs#L64) and [example usage](https://github.com/NuGet/NuGet.Client/blob/9dd33574b0cf5110692ee8e9401a39857fb5523a/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/AddPackageReferenceCommandRunner.cs#L114)). Whereas the VS/commandline implementations hardcodes to true. (see [vs definition](https://github.com/NuGet/NuGet.Client/blob/9dd33574b0cf5110692ee8e9401a39857fb5523a/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/DefaultVSCredentialServiceProvider.cs#L73) and [command definition](https://github.com/NuGet/NuGet.Client/blob/9dd33574b0cf5110692ee8e9401a39857fb5523a/src/NuGet.Clients/NuGet.CommandLine/Commands/Command.cs#L215)).

The cred provider exposes an environment variable to override the NuGet setting. Setting 'NUGET_CREDENTIALPROVIDER_FORCE_CANSHOWDIALOG_TO=true` will allow the system browser to pop up for mac and linux.  Please see the README for more information. I am able to confirm the environment variable on my local mac and was able to log in with the browser when the variable is set.

**Comment by embetten** [comment]
correction - my earlier statement regarding canShowDialog being hard coded only applies when the cred provider is invoked as a plugin from the nuget client. I see that you are invoking the cred provider .dll directly in "stand alone mode." In this scenario, the "NUGET_CREDENTIALPROVIDER_FORCE_CANSHOWDIALOG_TO" should not need to be set. Passing  -CanShowDialog as true will be respected in the latest version of the cred provider. I was again able to confirm this on a macOs. 

For linux, please ensure you are not running the cred provider from a ssh window. MSAL treats these as inherently non interactive, so the browser authentication will never be applicable from ssh. Please try RDP instead. 

If any further issues occur, please pass `-V Debug` to get some logs to furhter debug the issue.
