### ISSUE TITLE
Are the Requirements Correct?

### ISSUE THREAD

**Issue by twinter-amosfivesix** [microsoft/artifacts-credprovider#491]
The [requirements](https://github.com/microsoft/artifacts-credprovider) say:

> ### dotnet
> The default installation requires [dotnet SDK](https://www.microsoft.com/net/download) version 6.0.x.
>
> While the NuGet credential provider requires the dotnet runtime, the pip [artifacts-keyring](https://github.com/microsoft/artifacts-keyring) requires the dotnet SDK.

Questions:
1. Do I really need the SDK? Can I just use the runtimes? But see question 2
2. What is the pip artifacts key-ring and why would I care about it? I don't use pip with Azure Artifacts. Do I still need the SDK or can I just use the runtime? This statement in the requirements is pretty cryptic to someone who doesn't use Python and could definitely use some explanation. 
3. Do I really need .NET 6 now that .NET 7 and 8 are out? Or are the requirements really just 6+? If I'm doing .NET 8 development do I really need to install the .NET 8 SDK *and* the .NET 6 SDK?

Thanks! 😄

**Comment by embetten** [comment]
Only the runtime is required, thanks for pointing that out - we can update the docs. 

The artifacts-keyring is for python ecosystem development so you would only care about it if you were installing python packages from an Azure artifacts feed. The artifacts-keyring is a lightweight wrapper for the core cred provider which is why it is referenced in this readme. For the keyring it is currenlty incorrectly requiring the sdk - until we release the next version with this change https://github.com/microsoft/artifacts-keyring/pull/70

**Comment by twinter-amosfivesix** [comment]
@embetten Thanks!

Any thoughts on the .NET versions? Do I really need 6 or can I just use 8?

**Comment by embetten** [comment]
You can use 8 - the requirement is the runtime version 6 or greater.

**Comment by twinter-amosfivesix** [comment]
Can the requirements be updated to add "or later" after "The default installation requires [dotnet SDK](https://www.microsoft.com/net/download) version 6.0.x"?
